title: ETT 2024
preposition: at
description: >-
  International Conference on Emerging Topics in Typology \| June 10–12, 2024 \| Stockholm, Sweden
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ett2024.github.io" # the base hostname & protocol for your site, e.g. https://example.com

#theme: jekyll-theme-conference
remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Stockholm University
      img: '/su_logo.png'
      url: 'https://www.su.se/department-of-linguistics/'
    links:
      - name: Register
        relative_url: /register/
        disabled: true
      - name: Submit
        relative_url: /submit/
        disabled: true
      - name: Program
        relative_url: /program/
        disabled: true
      # - name: Talks
      #   relative_url: /talks/
      #   disabled: true
      # - name: Speakers
      #   relative_url: /speakers/
      #   disabled: true
      - name: Practical information
        relative_url: /location/
        disabled: true
      - name: Previous editions
        menu:
          - name: 2024 (current)
            disabled: true
          - name: 2021
            absolute_url: 'https://www.helsinki.fi/en/conferences/emerging-topics-typology'

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      # - name: Location
      #   disabled: true
      #   relative_url: /location/
      # - name: Program
      #   relative_url: /program/
      #   disabled: true
      # - name: Register
      #   disabled: true
      #   absolute_url: ''

  # Information boxes
  info_bars:
    - title: Welcome to the ETT 2024 conference website!
      color: primary
      main_only: true
      text: |
        This website is currently under construction, and information shown may not be accurate or current.
    - text: This website is currently under construction, and information shown may not be accurate or current.
      color: warning
      pages_only: true

  # Live indications
  live:
    date: 01.01.2020
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 47.37808, 8.53935
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Cat A
        color: info
      - name: Cat B
        color: success

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: true

  program:

    hide: true
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
